holon:
  datasource:
    tenant1:
      url: "jdbc:h2:mem:tenant1"
      username: "sa"
    tenant2:
      url: "jdbc:h2:mem:tenant2"
      username: "sa" 
      
  jwt:
    signature-algorithm: HS256
    sharedkey-base64: eWGZLlCrUjtBZwxgzcLPnA
